services:
  economy-bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/moderation-bot/Dockerfile
    env_file:
      - .env.economy
    volumes:
      - ./logs/economy-bot:/app/logs
    networks:
      - bridge
    depends_on:
      - mongo
  room-bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/rooms-bot/Dockerfile
    env_file:
      - .env.rooms
    volumes:
      - ./logs/rooms-bot:/app/logs
    networks:
      - bridge
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - ./data/db:/data/db
    expose:
      - '27017'
    networks:
      - bridge
    env_file:
      - .env.mongo

volumes:
  mongo-data:
    driver: local

networks:
  bridge:
