services:
  economy-bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/economy-bot/Dockerfile
    env_file:
      - .env.economy
    networks:
      - bridge
    depends_on:
      - mongo
  room-bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/rooms-bot/Dockerfile
    env_file:
      - .env.rooms
    networks:
      - bridge
    depends_on:
      - mongo
  close-bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/close-bot/Dockerfile
    env_file:
      - .env.close
    networks:
      - bridge
    depends_on:
      - mongo
  backup-bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/backup-bot/Dockerfile
    env_file:
      - .env.backup
    networks:
      - bridge
    depends_on:
      - mongo
  clan-bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/clan-bot/Dockerfile
    env_file:
      - .env.clan
    networks:
      - bridge
    depends_on:
      - mongo
  utils-bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/utils-bot/Dockerfile
    env_file:
      - .env.utils
    networks:
      - bridge
    depends_on:
      - mongo
  sup-bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/sup-bot/Dockerfile
    env_file:
      - .env.sup
    networks:
      - bridge
    depends_on:
      - mongo
  reports-bot:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/reports-bot/Dockerfile
    env_file:
      - .env.reports
    networks:
      - bridge
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - bridge
    env_file:
      - .env.mongo


volumes:
  mongo-data:
    driver: local

networks:
  bridge:
